### ISSUE TITLE
Road to v1

### ISSUE THREAD

**Issue by thomaslule** [thomaslule/twitch-channel#5]
- [x] Deprecate the functions `say`, `getTopClipper`, `getTwitchUserByName`
- [x] Doc: explain how to make the webhooks work
- [x] Log the webhook requests in debug level
- [x] Add an express middleware for webhooks
- [x] Delete unused options (secret)
- [x] Remove the dependency to Streamlabs (use the broadcaster token for the `host` event)
- [x] Doc: tell which options are needed for each event
- [x] Doc: give the spec of each event param
- [x] Explicitely allow partial option object
- [x] Add a "warn" log level
- [x] Create a `log` event for all logs
- [x] Add relevant EventSub events with scoped token
- [x] Add relevant IRC events
- [x] Dont extend `EventEmitter` anymore?
- [x] Merge sub and resub
- [x] Replace snake_case by camelCase for config options
- [x] Replace the stream-change-game event by something more generic
- [x] Check behaviour if we connect/disconnect/connect

**Comment by SebPautot** [comment]
After using this library for a while, I have few suggestions for you : 
- `TwitchChannel.disconnect` to disconnect from all webhooks. Also making the port reusable.
- Hype train event ?
- a clip event would be cool even though I don't think there is a webhook for that on Twitch (Streamlabs apparently has this)
- Change the streamer without having to redefine the TwitchChannel

**Comment by thomaslule** [comment]
Those are good ideas, thanks. I should definitely add more events.

> * `TwitchChannel.disconnect` to disconnect from all webhooks. Also making the port reusable.

the `disconnect` function should already do that 😮

**Comment by SebPautot** [comment]
The disconnect function already does that ? I thought it was only to disconnect from the chat because a webhook kept pinging the server with follow events even after I ".disconnect"ed it... I'll have to look into that then.

I also have an other request : 
The user changed webhook would be cool to have too

**Comment by thomaslule** [comment]
Yes, disconnect does that, it also unsubscribes from the webhook. But if at some point you had a webhook open that you just killed, twitch will continue to ping you with events for some time (but they will be ignored so it's okay).

I'm curious for the user changed webhook, what would be the use of that? I don't expect the broadcaster info to change very often 🤔

**Comment by SebPautot** [comment]
I run a Discord bot using twitch-channel, and the user changed webhook would allow me to store the new informations (because it allows me to limit the API requests) more dynamically. Currently I send a request each time a guild subscribes to a broadaster through a command but the broadcaster's infos are never updated unless the guild subscribes to the same broadcaster again.

Its use can be limited but quite usefull... sometimes ? (I know it's very rare, that's why the infos are never retrieved again after the subscription)

**Comment by edeuss** [comment]
@thomaslule How can you get the "stream-begin" webhook to work. Doesn't seem to receive info on stream start sub/resub and those ones work).

**Comment by thomaslule** [comment]
@EliasDeuss I dont reproduce it on my side (I get the event) but I opened an issue https://github.com/thomaslule/twitch-channel/issues/11

**Comment by thomaslule** [comment]
v1 released
